In [4]:
### import danych

import numpy as np

initial_inputs_1 = np.load('function_1/initial_inputs.npy')
initial_outputs_1 = np.load('function_1/initial_outputs.npy')
print(initial_inputs_1.shape)
print(initial_outputs_1.shape)

initial_inputs_2 = np.load('function_2/initial_inputs.npy')
initial_outputs_2 = np.load('function_2/initial_outputs.npy')
print(initial_inputs_2.shape)
print(initial_outputs_2.shape)

initial_inputs_3 = np.load('function_3/initial_inputs.npy')
initial_outputs_3 = np.load('function_3/initial_outputs.npy')
print(initial_inputs_3.shape)
print(initial_outputs_3.shape)

initial_inputs_4 = np.load('function_4/initial_inputs.npy')
initial_outputs_4 = np.load('function_4/initial_outputs.npy')
print(initial_inputs_4.shape)
print(initial_outputs_4.shape)

initial_inputs_5 = np.load('function_5/initial_inputs.npy')
initial_outputs_5 = np.load('function_5/initial_outputs.npy')
print(initial_inputs_5.shape)
print(initial_outputs_5.shape)

initial_inputs_6 = np.load('function_6/initial_inputs.npy')
initial_outputs_6 = np.load('function_6/initial_outputs.npy')
print(initial_inputs_6.shape)
print(initial_outputs_6.shape)

initial_inputs_7 = np.load('function_7/initial_inputs.npy')
initial_outputs_7 = np.load('function_7/initial_outputs.npy')
print(initial_inputs_7.shape)
print(initial_outputs_7.shape)

initial_inputs_8 = np.load('function_8/initial_inputs.npy')
initial_outputs_8 = np.load('function_8/initial_outputs.npy')
print(initial_inputs_8.shape)
print(initial_outputs_8.shape)
print(initial_inputs_1)
print(initial_outputs_1)


(10, 2)
(10,)
(10, 2)
(10,)
(15, 3)
(15,)
(30, 4)
(30,)
(20, 4)
(20,)
(20, 5)
(20,)
(30, 6)
(30,)
(40, 8)
(40,)
[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048]


In [5]:
import numpy as np

new_inputs = [
    np.array([0.67543 , 0.748945]),
    np.array([0.058084, 0.866176]),
    np.array([0.463538, 0.585335, 0.311607]),
    np.array([0.531561, 0.342526, 0.397711, 0.198366]),
    np.array([0.366362, 0.45607 , 0.785176, 0.199674]),
    np.array([0.743898, 0.127473, 0.738098, 0.636447, 0.075186]),
    np.array([0.948886, 0.965632, 0.808397, 0.304614, 0.097672, 0.684233]),
    np.array([0.055773, 0.01307 , 0.064056, 0.0, 0.414379, 0.703072, 0.421898, 0.902928])
]

new_outputs = [
    -1.5565803874270654e-13,
    0.0955018208493566,
    -0.06028346791026517,
    -4.374400058991476,
    0.4422272252688193,
    -0.8355518759421117,
    0.03450791140551037,
    9.7185482895031
]

In [6]:
# Function 1
initial_inputs_1_1 = np.vstack([initial_inputs_1, new_inputs[0].reshape(1, -1)])
initial_outputs_1_1 = np.append(initial_outputs_1, new_outputs[0])

# Function 2
initial_inputs_2_1 = np.vstack([initial_inputs_2, new_inputs[1].reshape(1, -1)])
initial_outputs_2_1 = np.append(initial_outputs_2, new_outputs[1])

# Function 3
initial_inputs_3_1 = np.vstack([initial_inputs_3, new_inputs[2].reshape(1, -1)])
initial_outputs_3_1 = np.append(initial_outputs_3, new_outputs[2])

# Function 4
initial_inputs_4_1 = np.vstack([initial_inputs_4, new_inputs[3].reshape(1, -1)])
initial_outputs_4_1 = np.append(initial_outputs_4, new_outputs[3])

# Function 5
initial_inputs_5_1 = np.vstack([initial_inputs_5, new_inputs[4].reshape(1, -1)])
initial_outputs_5_1 = np.append(initial_outputs_5, new_outputs[4])

# Function 6
initial_inputs_6_1 = np.vstack([initial_inputs_6, new_inputs[5].reshape(1, -1)])
initial_outputs_6_1 = np.append(initial_outputs_6, new_outputs[5])

# Function 7
initial_inputs_7_1 = np.vstack([initial_inputs_7, new_inputs[6].reshape(1, -1)])
initial_outputs_7_1 = np.append(initial_outputs_7, new_outputs[6])

# Function 8
initial_inputs_8_1 = np.vstack([initial_inputs_8, new_inputs[7].reshape(1, -1)])
initial_outputs_8_1 = np.append(initial_outputs_8, new_outputs[7])

In [7]:
print(initial_inputs_1_1)
print(initial_outputs_1_1)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.67543    0.748945  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048 -1.55658039e-013]


In [8]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern

np.random.seed(42)

def expected_improvement(X_candidates, model, y_best, xi=0.01):
    mu, sigma = model.predict(X_candidates, return_std=True)
    sigma = sigma.reshape(-1, 1)
    
    with np.errstate(divide='warn'):
        improvement = mu - y_best - xi
        Z = improvement / sigma
        ei = improvement * norm.cdf(Z) + sigma * norm.pdf(Z)
        ei[sigma == 0.0] = 0.0
    
    return ei.flatten()

def choose_next_point_bo(X, y, n_candidates=5000):
    dim = X.shape[1]
    
    # fit GP model
    kernel = Matern(
        length_scale=0.5, 
        length_scale_bounds=(1e-3, 10),
        nu=2.5)

    model = GaussianProcessRegressor(
        kernel=kernel,
        alpha=1e-3,
        normalize_y=True)
    model.fit(X, y)
    
    # generate candidates
    X_candidates = np.random.uniform(0, 1, (n_candidates, dim))
    
    # compute acquisition
    y_best = np.max(y)
    mu, sigma = model.predict(X_candidates, return_std=True)
    
    # simple acquisition: exploitation + uncertainty
    score = mu + 0.1 * sigma
    
    return X_candidates[np.argmax(score)]

def format_query(x):
    return "-".join([f"{xi:.6f}" for xi in x])

In [9]:
import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [10]:
x1_new = choose_next_point_bo(initial_inputs_1, initial_outputs_1)
x2_new = choose_next_point_bo(initial_inputs_2, initial_outputs_2)
x3_new = choose_next_point_bo(initial_inputs_3, initial_outputs_3)
x4_new = choose_next_point_bo(initial_inputs_4, initial_outputs_4)
x5_new = choose_next_point_bo(initial_inputs_5, initial_outputs_5)
x6_new = choose_next_point_bo(initial_inputs_6, initial_outputs_6)
x7_new = choose_next_point_bo(initial_inputs_7, initial_outputs_7)
x8_new = choose_next_point_bo(initial_inputs_8, initial_outputs_8)

In [14]:
print(np.round(x1_new, 6))
print(np.round(x2_new, 6))
print(np.round(x3_new, 6))
print(np.round(x4_new, 6))
print(np.round(x5_new, 6))
print(np.round(x6_new, 6))
print(np.round(x7_new, 6))
print(np.round(x8_new, 6))

[0.080919 0.40298 ]
[0.879273 0.779203]
[0.59192  0.7255   0.079854]
[0.416983 0.452178 0.388383 0.310864]
[0.158875 0.808215 0.943956 0.901422]
[0.48091  0.425612 0.348942 0.809975 0.255399]
[0.580779 0.526972 0.351037 0.493213 0.365097 0.657931]
[0.122085 0.080745 0.011016 0.224789 0.742507 0.480219 0.16568  0.248194]


[0.12208498 0.08074468 0.01101564 0.22478851 0.74250737 0.48021912
 0.16568004 0.24819353]
