In [11]:
### import danych

import numpy as np

initial_inputs_1 = np.load('function_1/initial_inputs.npy')
initial_outputs_1 = np.load('function_1/initial_outputs.npy')
print(initial_inputs_1.shape)
print(initial_outputs_1.shape)

initial_inputs_2 = np.load('function_2/initial_inputs.npy')
initial_outputs_2 = np.load('function_2/initial_outputs.npy')
print(initial_inputs_2.shape)
print(initial_outputs_2.shape)

initial_inputs_3 = np.load('function_3/initial_inputs.npy')
initial_outputs_3 = np.load('function_3/initial_outputs.npy')
print(initial_inputs_3.shape)
print(initial_outputs_3.shape)

initial_inputs_4 = np.load('function_4/initial_inputs.npy')
initial_outputs_4 = np.load('function_4/initial_outputs.npy')
print(initial_inputs_4.shape)
print(initial_outputs_4.shape)

initial_inputs_5 = np.load('function_5/initial_inputs.npy')
initial_outputs_5 = np.load('function_5/initial_outputs.npy')
print(initial_inputs_5.shape)
print(initial_outputs_5.shape)

initial_inputs_6 = np.load('function_6/initial_inputs.npy')
initial_outputs_6 = np.load('function_6/initial_outputs.npy')
print(initial_inputs_6.shape)
print(initial_outputs_6.shape)

initial_inputs_7 = np.load('function_7/initial_inputs.npy')
initial_outputs_7 = np.load('function_7/initial_outputs.npy')
print(initial_inputs_7.shape)
print(initial_outputs_7.shape)

initial_inputs_8 = np.load('function_8/initial_inputs.npy')
initial_outputs_8 = np.load('function_8/initial_outputs.npy')
print(initial_inputs_8.shape)
print(initial_outputs_8.shape)
print(initial_inputs_1)
print(initial_outputs_1)


(10, 2)
(10,)
(10, 2)
(10,)
(15, 3)
(15,)
(30, 4)
(30,)
(20, 4)
(20,)
(20, 5)
(20,)
(30, 6)
(30,)
(40, 8)
(40,)
[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048]


In [2]:
### 1 round

In [12]:
import numpy as np

new_inputs_2 = [
    np.array([0.67543 , 0.748945]),
    np.array([0.058084, 0.866176]),
    np.array([0.463538, 0.585335, 0.311607]),
    np.array([0.531561, 0.342526, 0.397711, 0.198366]),
    np.array([0.366362, 0.45607 , 0.785176, 0.199674]),
    np.array([0.743898, 0.127473, 0.738098, 0.636447, 0.075186]),
    np.array([0.948886, 0.965632, 0.808397, 0.304614, 0.097672, 0.684233]),
    np.array([0.055773, 0.01307 , 0.064056, 0.0, 0.414379, 0.703072, 0.421898, 0.902928])
]

new_outputs_2 = [
    -1.5565803874270654e-13,
    0.0955018208493566,
    -0.06028346791026517,
    -4.374400058991476,
    0.4422272252688193,
    -0.8355518759421117,
    0.03450791140551037,
    9.7185482895031
]

In [13]:
# Function 1
initial_inputs_1_1 = np.vstack([initial_inputs_1, new_inputs_2[0].reshape(1, -1)])
initial_outputs_1_1 = np.append(initial_outputs_1, new_outputs[0])

# Function 2
initial_inputs_2_1 = np.vstack([initial_inputs_2, new_inputs_2[1].reshape(1, -1)])
initial_outputs_2_1 = np.append(initial_outputs_2, new_outputs_2[1])

# Function 3
initial_inputs_3_1 = np.vstack([initial_inputs_3, new_inputs_2[2].reshape(1, -1)])
initial_outputs_3_1 = np.append(initial_outputs_3, new_outputs_2[2])

# Function 4
initial_inputs_4_1 = np.vstack([initial_inputs_4, new_inputs_2[3].reshape(1, -1)])
initial_outputs_4_1 = np.append(initial_outputs_4, new_outputs_2[3])

# Function 5
initial_inputs_5_1 = np.vstack([initial_inputs_5, new_inputs_2[4].reshape(1, -1)])
initial_outputs_5_1 = np.append(initial_outputs_5, new_outputs_2[4])

# Function 6
initial_inputs_6_1 = np.vstack([initial_inputs_6, new_inputs_2[5].reshape(1, -1)])
initial_outputs_6_1 = np.append(initial_outputs_6, new_outputs_2[5])

# Function 7
initial_inputs_7_1 = np.vstack([initial_inputs_7, new_inputs_2[6].reshape(1, -1)])
initial_outputs_7_1 = np.append(initial_outputs_7, new_outputs_2[6])

# Function 8
initial_inputs_8_1 = np.vstack([initial_inputs_8, new_inputs_2[7].reshape(1, -1)])
initial_outputs_8_1 = np.append(initial_outputs_8, new_outputs_2[7])

In [14]:
print(initial_inputs_1_1)
print(initial_outputs_1_1)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.67543    0.748945  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048 -1.25368270e-230]


In [15]:
##2 round

In [18]:
import numpy as np

new_inputs_3= [
    np.array([0.080919, 0.402980]),
    np.array([0.879273, 0.779203]),
    np.array([0.591920, 0.725500, 0.079854]),
    np.array([0.416983, 0.452178, 0.388383, 0.310864]),
    np.array([0.158875, 0.808215, 0.943956, 0.901422]),
    np.array([0.480910, 0.425612, 0.348942, 0.809975, 0.255399]),
    np.array([0.580779, 0.526972, 0.351037, 0.493213, 0.365097, 0.657931]),
    np.array([0.122085, 0.080745, 0.011016, 0.224789, 0.742507, 0.480219, 0.165680, 0.248194])
]

    
new_outputs_3 = [
    5.509906308883369e-82,
    0.3738808937524562,
    -0.048697205754457885,
    -1.000594963545399,
    1402.9211179435067,
    -0.5959761333368416,
    0.7946428203299398,
    9.9293867977869]

In [19]:
# Function 1
initial_inputs_1_3 = np.vstack([initial_inputs_1_1, new_inputs_3[0].reshape(1, -1)])
initial_outputs_1_3 = np.append(initial_outputs_1_1, new_outputs_3[0])

# Function 2
initial_inputs_2_3 = np.vstack([initial_inputs_2_1, new_inputs_3[1].reshape(1, -1)])
initial_outputs_2_3 = np.append(initial_outputs_2_1, new_outputs_3[1])

# Function 3
initial_inputs_3_3 = np.vstack([initial_inputs_3_1, new_inputs_3[2].reshape(1, -1)])
initial_outputs_3_3 = np.append(initial_outputs_3_1, new_outputs_3[2])

# Function 4
initial_inputs_4_3 = np.vstack([initial_inputs_4_1, new_inputs_3[3].reshape(1, -1)])
initial_outputs_4_3 = np.append(initial_outputs_4_1, new_outputs_3[3])

# Function 5
initial_inputs_5_3 = np.vstack([initial_inputs_5_1, new_inputs_3[4].reshape(1, -1)])
initial_outputs_5_3 = np.append(initial_outputs_5_1, new_outputs_3[4])

# Function 6
initial_inputs_6_3 = np.vstack([initial_inputs_6_1, new_inputs_3[5].reshape(1, -1)])
initial_outputs_6_3 = np.append(initial_outputs_6_1, new_outputs_3[5])

# Function 7
initial_inputs_7_3 = np.vstack([initial_inputs_7_1, new_inputs_3[6].reshape(1, -1)])
initial_outputs_7_3 = np.append(initial_outputs_7_1, new_outputs_3[6])

# Function 8
initial_inputs_8_3 = np.vstack([initial_inputs_8_1, new_inputs_3[7].reshape(1, -1)])
initial_outputs_8_3 = np.append(initial_outputs_8_1, new_outputs_3[7])
print(initial_inputs_1_3)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.67543    0.748945  ]
 [0.080919   0.40298   ]]


In [20]:
## 3 round

In [21]:
new_inputs_4 = [
    np.array([0.411765, 0.096892]),
    np.array([0.738382, 0.987009]),
    np.array([0.531437, 0.743237, 0.013497]),
    np.array([0.396863, 0.455675, 0.411971, 0.235379]),
    np.array([0.354101, 0.886366, 0.786340, 0.961742]),
    np.array([0.558005, 0.311919, 0.419502, 0.759493, 0.247187]),
    np.array([0.062461, 0.615847, 0.234084, 0.179148, 0.347001, 0.640961]),
    np.array([0.186668, 0.054730, 0.042491, 0.001464, 0.233729, 0.866517, 0.452104, 0.923183])
]

new_outputs_4 = [
    4.587011254852277e-74,
    0.4609249240946225,
    -0.07946811025466351,
    -2.500432435581881,
    1385.0449993878708,
    -0.534159273108338,
    1.1115341369151137,
    9.4986408113226
]

In [22]:
# Function 1
initial_inputs_1_4 = np.vstack([initial_inputs_1_3, new_inputs_4[0].reshape(1, -1)])
initial_outputs_1_4 = np.append(initial_outputs_1_3, new_outputs_4[0])

# Function 2
initial_inputs_2_4 = np.vstack([initial_inputs_2_3, new_inputs_4[1].reshape(1, -1)])
initial_outputs_2_4 = np.append(initial_outputs_2_3, new_outputs_4[1])

# Function 3
initial_inputs_3_4 = np.vstack([initial_inputs_3_3, new_inputs_4[2].reshape(1, -1)])
initial_outputs_3_4 = np.append(initial_outputs_3_3, new_outputs_4[2])

# Function 4
initial_inputs_4_4 = np.vstack([initial_inputs_4_3, new_inputs_4[3].reshape(1, -1)])
initial_outputs_4_4 = np.append(initial_outputs_4_3, new_outputs_4[3])

# Function 5
initial_inputs_5_4 = np.vstack([initial_inputs_5_3, new_inputs_4[4].reshape(1, -1)])
initial_outputs_5_4 = np.append(initial_outputs_5_3, new_outputs_4[4])

# Function 6
initial_inputs_6_4 = np.vstack([initial_inputs_6_3, new_inputs_4[5].reshape(1, -1)])
initial_outputs_6_4 = np.append(initial_outputs_6_3, new_outputs_4[5])

# Function 7
initial_inputs_7_4 = np.vstack([initial_inputs_7_3, new_inputs_4[6].reshape(1, -1)])
initial_outputs_7_4 = np.append(initial_outputs_7_3, new_outputs_4[6])

# Function 8
initial_inputs_8_4 = np.vstack([initial_inputs_8_3, new_inputs_4[7].reshape(1, -1)])
initial_outputs_8_4 = np.append(initial_outputs_8_3, new_outputs_4[7])

print(initial_inputs_1_4)
print(initial_outputs_1_4)
print(initial_inputs_8_4)
print(initial_outputs_8_4)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.67543    0.748945  ]
 [0.080919   0.40298   ]
 [0.411765   0.096892  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048 -1.25368270e-230  5.50990631e-082
  4.58701125e-074]
[[0.60499445 0.29221502 0.90845275 0.35550624 0.20166872 0.57533801
  0.31031095 0.73428138]
 [0.17800696 0.56622265 0.99486184 0.21032501 0.32015266 0.70790879
  0.63538449 0.10713163]
 [0.00907698 0.81162615 0.52052036 0.07568668 0.26511183 0.09165169
  0.59241515 0.36732026]
 [0.50602816 0.65373012 0.36341078 0.17798105 0.0937283  0.19742533
  0.7558269  0.29247234]
 [0.35990926 0.24907568 0.49599717 0.70921498 0.11498719 0.28920692
  0.5572

In [ ]:
#4 th round

In [23]:
new_inputs_5 = [
    np.array([0.058084, 0.866176]),
    np.array([0.304242, 0.524756]),
    np.array([0.514744, 0.623185, 0.351839]),
    np.array([0.607545, 0.170524, 0.065052, 0.948886]),
    np.array([0.762340, 0.344398, 0.146055, 0.728896]),
    np.array([0.969585, 0.775133, 0.939499, 0.894827, 0.597900]),
    np.array([0.986887, 0.772245, 0.198716, 0.005522, 0.815461, 0.706857]),
    np.array([0.710208, 0.012083, 0.316592, 0.179432, 0.912383, 0.583334, 0.284515, 0.036740])
]

new_outputs_5 = [
    -1.253682700730567e-230,
    0.06640939855571966,
    -0.04404362668564711,
    -22.068779140652996,
    20.7235582261439,
    -1.8772762082337837,
    0.0007255445582414515,
    9.0716840504565
]

In [24]:
# Function 1
initial_inputs_1_5 = np.vstack([initial_inputs_1_4, new_inputs_5[0].reshape(1, -1)])
initial_outputs_1_5 = np.append(initial_outputs_1_4, new_outputs_5[0])

# Function 2
initial_inputs_2_5 = np.vstack([initial_inputs_2_4, new_inputs_5[1].reshape(1, -1)])
initial_outputs_2_5 = np.append(initial_outputs_2_4, new_outputs_5[1])

# Function 3
initial_inputs_3_5 = np.vstack([initial_inputs_3_4, new_inputs_5[2].reshape(1, -1)])
initial_outputs_3_5 = np.append(initial_outputs_3_4, new_outputs_5[2])

# Function 4
initial_inputs_4_5 = np.vstack([initial_inputs_4_4, new_inputs_5[3].reshape(1, -1)])
initial_outputs_4_5 = np.append(initial_outputs_4_4, new_outputs_5[3])

# Function 5
initial_inputs_5_5 = np.vstack([initial_inputs_5_4, new_inputs_5[4].reshape(1, -1)])
initial_outputs_5_5 = np.append(initial_outputs_5_4, new_outputs_5[4])

# Function 6
initial_inputs_6_5 = np.vstack([initial_inputs_6_4, new_inputs_5[5].reshape(1, -1)])
initial_outputs_6_5 = np.append(initial_outputs_6_4, new_outputs_5[5])

# Function 7
initial_inputs_7_5 = np.vstack([initial_inputs_7_4, new_inputs_5[6].reshape(1, -1)])
initial_outputs_7_5 = np.append(initial_outputs_7_4, new_outputs_5[6])

# Function 8
initial_inputs_8_5 = np.vstack([initial_inputs_8_4, new_inputs_5[7].reshape(1, -1)])
initial_outputs_8_5 = np.append(initial_outputs_8_4, new_outputs_5[7])

print(initial_inputs_1_5)
print(initial_outputs_1_5)
print(initial_inputs_8_5)
print(initial_outputs_8_5)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.67543    0.748945  ]
 [0.080919   0.40298   ]
 [0.411765   0.096892  ]
 [0.058084   0.866176  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048 -1.25368270e-230  5.50990631e-082
  4.58701125e-074 -1.25368270e-230]
[[0.60499445 0.29221502 0.90845275 0.35550624 0.20166872 0.57533801
  0.31031095 0.73428138]
 [0.17800696 0.56622265 0.99486184 0.21032501 0.32015266 0.70790879
  0.63538449 0.10713163]
 [0.00907698 0.81162615 0.52052036 0.07568668 0.26511183 0.09165169
  0.59241515 0.36732026]
 [0.50602816 0.65373012 0.36341078 0.17798105 0.0937283  0.19742533
  0.7558269  0.29247234]
 [0.35990926 0.24907568 0.49599717

In [28]:
inputs_15 = [
    initial_inputs_1_5,
    initial_inputs_2_5,
    initial_inputs_3_5,
    initial_inputs_4_5,
    initial_inputs_5_5,
    initial_inputs_6_5,
    initial_inputs_7_5,
    initial_inputs_8_5
]

outputs_15 = [
    initial_outputs_1_5,
    initial_outputs_2_5,
    initial_outputs_3_5,
    initial_outputs_4_5,
    initial_outputs_5_5,
    initial_outputs_6_5,
    initial_outputs_7_5,
    initial_outputs_8_5
]

for i, (inp, out) in enumerate(zip(inputs_15, outputs_15), start=1):
    print(f"Function {i}:")
    print(" inputs shape:", inp.shape)
    print(" outputs shape:", out.shape)
    print()

Function 1:
 inputs shape: (14, 2)
 outputs shape: (14,)

Function 2:
 inputs shape: (14, 2)
 outputs shape: (14,)

Function 3:
 inputs shape: (19, 3)
 outputs shape: (19,)

Function 4:
 inputs shape: (34, 4)
 outputs shape: (34,)

Function 5:
 inputs shape: (24, 4)
 outputs shape: (24,)

Function 6:
 inputs shape: (24, 5)
 outputs shape: (24,)

Function 7:
 inputs shape: (34, 6)
 outputs shape: (34,)

Function 8:
 inputs shape: (44, 8)
 outputs shape: (44,)



In [29]:
import numpy as np
import tensorflow as tf

np.random.seed(42)
tf.random.set_seed(42)

# ----------------------
# Build model (slightly regularised)
# ----------------------
def build_model(dim):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation='relu', input_shape=(dim,)),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1)
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
        loss='mse'
    )
    return model


# ----------------------
# Train ensemble
# ----------------------
def train_ensemble(X, y, n_models=5):
    models = []
    for _ in range(n_models):
        model = build_model(X.shape[1])
        model.fit(X, y, epochs=120, verbose=0)
        models.append(model)
    return models


# ----------------------
# Ensemble prediction
# ----------------------
def ensemble_predict(models, x):
    preds = np.array([m.predict(x, verbose=0)[0, 0] for m in models])
    return preds.mean(), preds.std()


# ----------------------
# Gradient ascent using ONE model
# ----------------------
def gradient_ascent(model, x_init, steps=40, lr=0.01):
    x = tf.Variable(x_init.reshape(1, -1), dtype=tf.float32)

    for _ in range(steps):
        with tf.GradientTape() as tape:
            tape.watch(x)
            pred = model(x)

        grads = tape.gradient(pred, x)

        # clip gradients (stability)
        grads = tf.clip_by_value(grads, -0.1, 0.1)

        x.assign_add(lr * grads)
        x.assign(tf.clip_by_value(x, 0.0, 1.0))

    return x.numpy().flatten()


# ----------------------
# MAIN STRATEGY
# ----------------------
def choose_next_point_ensemble(X, y):

    dim = X.shape[1]

    # ----------------------
    # 1. Train ensemble
    # ----------------------
    models = train_ensemble(X, y, n_models=5)

    # ----------------------
    # 2. Generate candidates
    # ----------------------
    candidates = []

    best_x = X[np.argmax(y)]

    # (A) Gradient-based candidates
    for m in models:
        x0 = best_x if np.random.rand() < 0.7 else np.random.uniform(0, 1, dim)
        x_new = gradient_ascent(m, x0)
        candidates.append(x_new)

    # (B) Random exploration
    for _ in range(5):
        candidates.append(np.random.uniform(0, 1, dim))

    # (C) Local perturbations
    for _ in range(5):
        noise = np.random.normal(0, 0.05, dim)
        x_new = np.clip(best_x + noise, 0, 1)
        candidates.append(x_new)

    # ----------------------
    # 3. Score candidates
    # ----------------------
    best_score = -np.inf
    best_candidate = None

    for x in candidates:
        x_tf = x.reshape(1, -1)

        mu, sigma = ensemble_predict(models, x_tf)

        # gradient norm (importance)
        with tf.GradientTape() as tape:
            xt = tf.Variable(x_tf, dtype=tf.float32)
            tape.watch(xt)
            pred = models[0](xt)

        grad = tape.gradient(pred, xt).numpy()
        grad_norm = np.linalg.norm(grad)

        # FINAL SCORE
        score = mu + 0.2 * sigma + 0.05 * grad_norm

        if score > best_score:
            best_score = score
            best_candidate = x

    return best_candidate


# ----------------------
# FORMAT
# ----------------------
def format_query(x):
    return "-".join([f"{xi:.6f}" for xi in x])


# ----------------------
# RUN FOR ALL FUNCTIONS
# ----------------------
queries = []

for i in range(8):
    X = inputs_15[i]
    y = outputs_15[i]

    q = choose_next_point_ensemble(X, y)
    queries.append(q)


# ----------------------
# PRINT
# ----------------------
for i, q in enumerate(queries):
    print(f"Function {i+1}: {format_query(q)}")

C:\Users\Evaluer\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Function 1: 0.708073-0.020584
Function 2: 0.742636-0.966564
Function 3: 0.198716-0.005522-0.815461
Function 4: 0.510747-0.417411-0.222108-0.119865
Function 5: 0.118875-0.848215-0.983956-0.941422
Function 6: 0.518005-0.297469-0.387221-0.740676-0.207187
Function 7: 0.017896-0.451673-0.243562-0.178118-0.380429-0.770969
Function 8: 0.082085-0.040745-0.000000-0.264789-0.782506-0.520218-0.125680-0.288193


In [30]:
#Function 1: 0.708073-0.020584
#Function 2: 0.742636-0.966564
#Function 3: 0.198716-0.005522-0.815461
#Function 4: 0.510747-0.417411-0.222108-0.119865
#Function 5: 0.118875-0.848215-0.983956-0.941422
#Function 6: 0.518005-0.297469-0.387221-0.740676-0.207187
#Function 7: 0.017896-0.451673-0.243562-0.178118-0.380429-0.770969
#Function 8: 0.082085-0.040745-0.000000-0.264789-0.782506-0.520218-0.125680-0.288193